CREATE TABLE SEATCATEGORY (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  NAME VARCHAR(100) DEFAULT NULL,
  HALL_ID BIGINT DEFAULT NULL,
  CAPACITY INT DEFAULT NULL
);
CREATE SEQUENCE seatCategory_id_seq START WITH 1 INCREMENT BY 1;
CREATE INDEX IX_SEATCATEGORY_HALL ON SEATCATEGORY(HALL_ID);

ALTER TABLE EVENTTICKETPRICE ADD COLUMN SEATCATEGORY_ID BIGINT DEFAULT NULL;
ALTER TABLE SEATCATEGORY ADD COLUMN DESCRIPTION TEXT DEFAULT NULL;

ALTER TABLE SEATCATEGORY ADD COLUMN PARTOFTOTALCAPACITY TINYINT DEFAULT 1;

ALTER TABLE EVENTTICKETPRICE ADD COLUMN DTYPE VARCHAR(100) DEFAULT NULL;
ALTER TABLE EVENTTICKETPRICE ADD COLUMN HALL_ID BIGINT DEFAULT NULL;
UPDATE EVENTTICKETPRICE SET DTYPE = "EventTicketPrice";
