/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  rborowski
 * Created: 02.08.2024
 */

ALTER TABLE EVENTTICKETPRICE ADD COLUMN DTYPE VARCHAR(100) DEFAULT NULL;
ALTER TABLE EVENTTICKETPRICE ADD COLUMN VENUE_ID BIGINT DEFAULT NULL;
ALTER TABLE MAILTEMPLATE ADD COLUMN BCC VARCHAR(250) DEFAULT NULL;
ALTER TABLE VENUECONTACT ADD COLUMN NOTIFYONRESERVATION TINYINT DEFAULT 0;

ALTER TABLE RESERVATIONTICKET CHANGE CATEGORY_ID PRICECATEGORY_ID BIGINT DEFAULT NULL;
ALTER TABLE RESERVATIONTICKET ADD COLUMN SEATCATEGORY_ID BIGINT DEFAULT NULL;

ALTER TABLE EVENT ADD COLUMN RESERVABLE TINYINT DEFAULT 0;
ALTER TABLE VENUE ADD COLUMN PUBLICNOTES TEXT DEFAULT NULL;

ALTER TABLE SEASONVENUE ADD COLUMN SEASONNOTES TEXT DEFAULT NULL;