INSERT INTO MAILTEMPLATE (ID, SHORTCODE, NAME, DESCRIPTION) VALUES (nextval(mailTemplate_id_seq), "NOTIFY_VENUE_NEW", "Neue Buchung für Veranstaltungsort", "Wird an den Veranstaltungsort gesendet, wenn eine neue Buchung eingeht.");

INSERT INTO MAILTEMPLATE (ID, SHORTCODE, NAME, DESCRIPTION) VALUES (nextval(mailTemplate_id_seq), "NOTIFY_VENUE_CANCELED", "Buchung storniert für Veranstaltungsort", "Wird an den Veranstaltungsort gesendet, wenn eine Buchung storniert wurde.");

--
-- MAILACCOUNT TABLE
--
CREATE TABLE MAILACCOUNT (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  SMTPHOST VARCHAR(150) DEFAULT NULL,
  SMTPPORT INT DEFAULT NULL,
  SMTPTRANSPORTSECURITY VARCHAR(50) DEFAULT 'UNSET',
  SMTPUSER VARCHAR(150) DEFAULT NULL,
  SMTPPASSWORD VARCHAR(150) DEFAULT NULL,
  IMAPHOST VARCHAR(150) DEFAULT NULL,
  IMAPPORT INT DEFAULT NULL,
  IMAPTRANSPORTSECURITY VARCHAR(50) DEFAULT 'UNSET',
  IMAPUSER VARCHAR(150) DEFAULT NULL,
  IMAPPASSWORD VARCHAR(150) DEFAULT NULL
);
CREATE SEQUENCE mailAccount_id_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE SEASON ADD COLUMN MAILACCOUNT_ID BIGINT DEFAULT NULL;