
/**
 * Author:  rborowski
 * Created: 15.11.2024
 */

CREATE TABLE LICENSECONDITION (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  PRODUCTION_ID BIGINT DEFAULT NULL,
  AGENCY_ID BIGINT DEFAULT NULL,
  COMMERCIAL TINYINT DEFAULT NULL,
  GUARANTEE_AMOUNT DECIMAL(16,4) DEFAULT NULL,
  GUARANTEE_CURRENCY VARCHAR(5) DEFAULT NULL,
  FIXEDPRICE_AMOUNT DECIMAL(16,4) DEFAULT NULL,
  FIXEDPRICE_CURRENCY VARCHAR(5) DEFAULT NULL,
  TICKETSHARE_AMOUNT DECIMAL(16,4) DEFAULT NULL,
  TICKETSHARE_CURRENCY VARCHAR(5) DEFAULT NULL,
  ADDITIONALCOST_AMOUNT DECIMAL(16,4) DEFAULT NULL,
  ADDITIONALCOST_CURRENCY VARCHAR(5) DEFAULT NULL,
  NOTES TEXT DEFAULT NULL
);
CREATE SEQUENCE licenseCondition_id_seq START WITH 1 INCREMENT BY 1;


CREATE INDEX IX_LICENSECONDITION_PRODUCTION ON LICENSECONDITION(PRODUCTION_ID);
CREATE INDEX IX_LICENSECONDITION_AGENCY ON LICENSECONDITION(AGENCY_ID);

ALTER TABLE PRODUCTION ADD COLUMN EXTERNALID VARCHAR(250) DEFAULT NULL;
ALTER TABLE PRODUCTION ADD COLUMN INTERNALNOTE TEXT DEFAULT NULL;

ALTER TABLE PRODUCTION CHANGE INTERNALNOTES INTERNALNOTE TEXT DEFAULT NULL;

CREATE TABLE PRODUCTIONMEDIUM (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  PRODUCTION_ID BIGINT DEFAULT NULL,
  NAME VARCHAR(150) DEFAULT NULL,
  FORMAT VARCHAR(50) DEFAULT NULL,
  REFERENCE VARCHAR(300) DEFAULT NULL,
  NOTE TEXT DEFAULT NULL
);
CREATE SEQUENCE productionMedium_id_seq START WITH 1 INCREMENT BY 1;


CREATE INDEX IX_PRODUCTIONMEDIUM_PRODUCTION ON PRODUCTIONMEDIUM(PRODUCTION_ID);

ALTER TABLE ATTACHMENT ADD COLUMN CHECKSUM VARCHAR(100) DEFAULT NULL;

ALTER TABLE ATTACHMENT CHANGE COLUMN COPYRIGHT COPYRIGHT VARCHAR(300) DEFAULT NULL;

ALTER TABLE MAILACCOUNT ADD COLUMN IMAPSENTFOLDER VARCHAR(200) DEFAULT "SENT";