/**
 * Author:  rborowski
 * Created: 01.01.2025
 */

CREATE TABLE SEASONPRICETEMPLATE (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  SEASON_ID BIGINT DEFAULT NULL,
  PRICECATEGORY_ID BIGINT DEFAULT NULL,
  PRICE_AMOUNT DECIMAL(16,4) DEFAULT NULL,
  PRICE_CURRENCY VARCHAR(5) DEFAULT NULL
);
CREATE SEQUENCE seasonPriceTemplate_id_seq START WITH 1 INCREMENT BY 1;


CREATE INDEX IX_SEASONPRICETEMPLATE_SEASON ON SEASONPRICETEMPLATE(SEASON_ID);
CREATE INDEX IX_SEASONPRICETEMPLATE_PRICECATEGORY ON SEASONPRICETEMPLATE(PRICECATEGORY_ID);

ALTER TABLE EVENTSERIAL ADD COLUMN SEASON_ID BIGINT DEFAULT NULL;