/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  rborowski
 * Created: 11.03.2025
 */

CREATE TABLE HALLCAPACITY (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  SEATCATEGORY_ID BIGINT DEFAULT NULL,
  HALL_ID BIGINT DEFAULT NULL,
  CAPACITY INT DEFAULT NULL,
  PARTOFTOTALCAPACITY TINYINT DEFAULT NULL
);
CREATE SEQUENCE hallCapacity_id_seq START WITH 1 INCREMENT BY 1;


CREATE INDEX IX_HALLCAPACITY_SEATCATEGORY ON HALLCAPACITY(SEATCATEGORY_ID);
CREATE INDEX IX_HALLCAPACITY_HALL ON HALLCAPACITY(HALL_ID);

INSERT INTO HALLCAPACITY (ID, SEATCATEGORY_ID, HALL_ID, CAPACITY, PARTOFTOTALCAPACITY)
SELECT ID, ID, HALL_ID, CAPACITY, PARTOFTOTALCAPACITY
FROM SEATCATEGORY;


SELECT * FROM EVENTTICKETPRICE WHERE SEATCATEGORY_ID IS NULL;