/**
 * Author:  rborowski
 * Created: 31.10.2023
 */

ALTER TABLE PRODUCTION ADD COLUMN FROMAGE INTEGER DEFAULT NULL;
ALTER TABLE PRODUCTION ADD COLUMN TOAGE INTEGER DEFAULT NULL;

ALTER TABLE EVENT ADD COLUMN SEASON_ID BIGINT NOT NULL;

CREATE TABLE SEASONVENUE (
  ID BIGINT PRIMARY KEY NOT NULL,
  CREATEUSER VARCHAR(50) DEFAULT NULL,
  CREATEDATE DATETIME DEFAULT NULL,
  MODIFYUSER VARCHAR(50) DEFAULT NULL,
  MODIFYDATE DATETIME DEFAULT NULL,
  SEASON_ID BIGINT DEFAULT NULL,
  VENUE_ID BIGINT DEFAULT NULL,
  SELFPROGRAMMING TINYINT DEFAULT NULL
);

ALTER TABLE VENUE ADD COLUMN POSTCODE VARCHAR(10) DEFAULT NULL;
ALTER TABLE VENUE ADD COLUMN CITY VARCHAR(100) DEFAULT NULL;

ALTER TABLE SEASON ADD COLUMN ISARCHIVED TINYINT DEFAULT 0;

ALTER TABLE VENUE ADD COLUMN INTERNALNOTES TEXT;

ALTER TABLE PRODUCTIONVERSION ADD COLUMN VERSIONNAME VARCHAR(30) DEFAULT "";

ALTER TABLE SEASON ADD COLUMN start DATE;
ALTER TABLE SEASON ADD COLUMN end DATE;