/**
 * Author:  rborowski
 * Created: 16.01.2024
 */

ALTER TABLE RESERVATIONTICKET ADD COLUMN CATEGORY_ID BIGINT DEFAULT NULL;

ALTER VIEW TICKETSALES AS
SELECT E.ID AS EVENT_ID, COALESCE(SUM(T.AMOUNT), 0) AS TICKETSSOLD 
FROM EVENT E 
LEFT OUTER JOIN RESERVATION R ON (R.EVENT_ID = E.ID) 
LEFT OUTER JOIN RESERVATIONTICKET T ON R.ID = T.RESERVATION_ID 
GROUP BY E.ID;

UPDATE RESERVATIONTICKET
JOIN EVENTTICKETPRICE ON RESERVATIONTICKET.PRICE_ID = EVENTTICKETPRICE.ID
SET RESERVATIONTICKET.CATEGORY_ID = EVENTTICKETPRICE.PRICECATEGORY_ID;

ALTER TABLE RESERVATIONTICKET ADD COLUMN PRICE_AMOUNT DECIMAL(16,4) DEFAULT NULL;
ALTER TABLE RESERVATIONTICKET ADD COLUMN PRICE_CURRENCY VARCHAR(5) DEFAULT NULL;

UPDATE RESERVATIONTICKET
JOIN EVENTTICKETPRICE ON RESERVATIONTICKET.PRICE_ID = EVENTTICKETPRICE.ID
SET RESERVATIONTICKET.PRICE_AMOUNT = EVENTTICKETPRICE.PRICE_AMOUNT,
RESERVATIONTICKET.PRICE_CURRENCY = EVENTTICKETPRICE.PRICE_CURRENCY;